apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-hostpath-sc