apiVersion: v1
kind: LimitRange
metadata:
  name: assignmentlimitrange 
  namespace: {{ .Values.namespace }}
spec:
  limits:
    - type: Container
      max:
        cpu: "2"
        memory: "2Gi"
      default:
        cpu: "100m"
        memory: "200Mi"
      defaultRequest:
        cpu: "5m"
        memory: "10Mi"