apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes: 
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage