apiVersion: v1
kind: ResourceQuota
metadata:
  name: assignmentquota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    pods: "20"
    requests.cpu: "4"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"