services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"


  backend:
    build:
      context: ./backend
    depends_on: 
      - db
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
    volumes:
      - .env:/app/.env
    ports:
      - "5000:5000"


  frontend:
    build:
      context: ./frontend
    depends_on: 
      - backend
    ports:
      - "80:80"