apiVersion: v1
kind: Service
metadata:
 name: frontend-expose
 namespace: {{ .Values.namespace }}
spec:
 type: NodePort
 selector:
   app: frontend
 ports:
 - nodePort: 30000
   protocol: TCP
   port: 80
   targetPort: 80