apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-configmap
  namespace: {{ .Values.namespace }}
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS test_table (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100)
    );

    INSERT INTO test_table (name) VALUES
    ('Grigo'),
    ('React.JS + Flask + PostgreSQL'),
    ('Kubernetes Assignment');